name: Build and Deploy to Azure

on:
  push:
    branches: [ "master", "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: foodreg1181792482.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Restaurant Service
        run: |
          docker build -t foodreg1181792482.azurecr.io/restaurant-service:latest ./RestaurantManagmentService
          docker push foodreg1181792482.azurecr.io/restaurant-service:latest

      - name: Build and push Admin Frontend
        run: |
          docker build -t foodreg1181792482.azurecr.io/admin-frontend:latest ./Admin-Frontend
          docker push foodreg1181792482.azurecr.io/admin-frontend:latest

      - name: Build and push Main Frontend
        run: |
          docker build -t foodreg1181792482.azurecr.io/main-frontend:latest ./Frontend
          docker push foodreg1181792482.azurecr.io/main-frontend:latest
